### ISSUE TITLE
如何修改打卡的地理位置

### ISSUE THREAD

**Issue by Crazydelishuoyuan** [expoli/zzu-jksb-public#3]
纯萌新,求大佬写的地理位置的代码在哪个地方。

**Comment by expoli** [comment]
地理位置并没有提供配置接口，采取了直接 ban 掉相应的地理位置获取的API的方法，具体实现刻意查看 action 配置文件

**Comment by expoli** [comment]
https://github.com/expoli/zzu-jksb-public/blob/fbf59d64675468ac84e9e337788cd2efb5ebdf8a/.github/workflows/python-app-with-env.yml#L41
